### ISSUE TITLE
null-objects and arrays not supported anymore in v2

### ISSUE THREAD

**Issue by mado0803** [asyncapi/converter-go#31]
**Description**

We have trouble with converted json files from 1.0.0 to 2.0.0 because objects and arrays are set to `null` which seems to not be allowed anymore in v2. Could the converter support this by either removing these lines or setting objects to { } and arrays to [ ]? 

**Reasons**

Errors when converting from version 1.0.0 to 2.0.0 as null'ed objects and arrays are not allowed.

**Attachments**

```json
 "customerId":{
    "description":"Unique Customer ID",
    "example":"5bca84f7-d648-4330-8e8d-ededd220a853",
    **"properties":null,
    "required":null,**
    "title":"Unique Customer ID",
    "type":"string"
 }
```
Edit: @fmvilas here. Edited the code for better readability.

**Comment by magicmatatjahu** [comment]
@mado0803 Hi! Thanks for issue. The main problem is that

```
"properties":null,
"required":null,
```

is not a valid case for JSON Schema. JSON Schema `properties` must be in form of JSON Object or not to be defined in schema, `required` in other hand must be in form od array or not to be defined in schema. I wonder if AsyncAPI (and also JSON Schema) had support in past `null` value for properties/required @fmvilas do you know something about it?

**Comment by fmvilas** [comment]
Hey @mado0803! Thanks for opening the issue. Are you using `converter-go` as a CLI or as a module? If it's as a CLI, can you try with https://github.com/asyncapi/converter-js/? @derberg can you take care of this issue?

**Comment by magicmatatjahu** [comment]
Also converter don't convert message payloads, schemas etc, but only adjust old naming from v1 to v2 like `topics` -> `channels`, so I don't think that there should be proposed any solution, inside the code.

**Comment by derberg** [comment]
We can't really take any action until we get some samples in my opinion. @mado0803 you are for sure using `converter-go` in a service that is responsible for conversion of old specs to new ones after they are registered in Kyma. Please share with us the spec that contains `customerId` schema, the version of the spec before the conversion and after conversion so we can see data before and after to really understand where is the problem

**Comment by derberg** [comment]
I see you are actually also using the JS converter in some UI https://github.com/kyma-project/console/blob/master/compass/package.json

would be great if you could confirm @mado0803 what is the status here

**Comment by mado0803** [comment]
Hello @derberg, 

I am sorry for the confusion caused by the issue. We implemented a fix on our side that ignores the null values when converting.

Best regards,
Marco.
