### ISSUE TITLE
Fix Sonarcloud code smell. Repeated usage of literals should be moved to constants.

### ISSUE THREAD

**Issue by smoya** [asyncapi/converter-go#46]
**Description**

Sonarcloud complains about the usage of a string literal several times on [internal/cli/cli.go](internal/cli/cli.go). It suggests moving it into a constant.

Here is the issue in Sonarcloud: https://sonarcloud.io/project/issues?id=asyncapi_converter-go&issues=AXSXW4_-fuClvfEIZXO2&open=AXSXW4_-fuClvfEIZXO2

**Expected result**

- A new constant or var should be created and use it. The var should contain the literal string `--toYAML`.
- The issue https://sonarcloud.io/project/issues?id=asyncapi_converter-go&issues=AXSXW4_-fuClvfEIZXO2&open=AXSXW4_-fuClvfEIZXO2 should be gone after the change has been done.

**Comment by rafaelrubbioli** [comment]
I would like to work on this one!

**Comment by smoya** [comment]
> I would like to work on this one!

That was so fast! Feel free to open a PR anytime. 

Thank you @rafaelrubbioli ! 🚀 🌔
